import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./Components/header";
import Footer from "./Components/footer";
import styles from "./globalStyling.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
          <Header title="Crack" />
          <main className={styles.main}>
            {children}
          </main>
          <Footer />
      </body>
    </html>
  );
}
